name: Build DataGenie Desktop

on:
  push:
    tags: ['v*']
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: DataGenie-Linux
            extension: ''
          - os: windows-latest
            artifact_name: DataGenie-Windows
            extension: '.exe'
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev build-essential
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build application
      run: python build.py
      
    - name: Test built application
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          echo "Skipping test on Windows (requires display)"
        else
          echo "Testing Linux build..."
          # Basic test to ensure executable was created
          ls -la dist/DataGenie${{ matrix.extension }}
        fi
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/DataGenie${{ matrix.extension }}
        
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/DataGenie${{ matrix.extension }}